=== OWASP/off/owasp.off.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/OWASP/off/blob/trunk/owasp.off.schema.json",
  "title": "Finding",
  "description": "OWASP Security Finding",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "maxLength": 128
    },
    "description": {
      "type": "string",
      "maxLength": 256
    },
    "detail": {
      "type": "string"
    },
    "severity": {
      "anyOf": [
        {
          "enum": [
            1,
            2,
            3,
            4,
            5
          ]
        },
        {
          "enum": [
            "low",
            "medium",
            "high"
          ]
        }
      ]
    },
    "confidence": {
      "enum": [
        "low",
        "medium",
        "high"
      ]
    },
    "priority": {
      "enum": [
        "low",
        "medium",
        "high"
      ]
    },
    "status": {
      "enum": [
        "new",
        "open",
        "closed",
        "re-opened"
      ]
    },
    "fingerprint": {
      "type": "string",
      "maxLength": 256
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "location": {
      "anyOf": [
        {
          "type": "string",
          "maxLength": 256
        },
        {
          "$ref": "#/definitions/host"
        }
      ]
    },
    "source": {
      "anyOf": [
        {
          "type": "string",
          "maxLength": 128
        },
        {
          "$ref": "#/definitions/source"
        }
      ]
    },
    "cvss": {
      "anyOf": [
        {
          "type": "number",
          "minimum": 0,
          "maximum": 10
        },
        {
          "$ref": "#/definitions/cvss"
        }
      ]
    },
    "cwes": {
      "type": "array",
      "maxItems": 15,
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "references": {
      "type": "array",
      "maxItems": 100,
      "items": {
        "anyOf": [
          {
            "type": "string",
            "format": "uri"
          },
          {
            "type": "object",
            "additionalProperties": true
          }
        ]
      }
    },
    "tags": {
      "type": "array",
      "maxItems": 100,
      "items": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "object",
            "additionalProperties": true
          }
        ]
      }
    }
  },
  "definitions": {
    "host": {
      "type": "object",
      "properties": {
        "hostname": {
          "type": "string",
          "maxLength": 128
        },
        "ipv4": {
          "type": "string",
          "format": "ipv4"
        },
        "ipv6": {
          "type": "string",
          "format": "ipv6"
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "protocol": {
          "type": "string",
          "maxLength": 20
        }
      },
      "additionalProperties": false
    },
    "coderef": {
      "type": "object",
      "properties": {
        "modulename": {
          "type": "string"
        },
        "filename": {
          "type": "string"
        },
        "linenum": {
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "cvss": {
      "type": "object",
      "properties": {
        "version": {
          "type": "number",
          "minimum": 2
        },
        "score": {
          "type": "number",
          "minimum": 0,
          "maximum": 10
        },
        "vector": {
          "type": "string",
          "maxLength": 128
        }
      },
      "additionalProperties": false
    },
    "source": {
      "type": "object",
      "properties": {
        "testType": {
          "type": "string",
          "maxLength": 50
        },
        "testProvider": {
          "type": "string",
          "maxLength": 128
        },
        "testRef": {
          "type": "string",
          "maxLength": 128
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "name",
    "description",
    "severity",
    "confidence",
    "timestamp",
    "location",
    "source"
  ],
  "additionalProperties": false
}

=== OWASP/off/example.finding.json
{
	"name": "Finding 1",
	"description": "Detailed description",
	"severity": "low",
	"confidence": "medium", 
	"fingerprint": "ABC", 
	"timestamp": "2017-09-14T16:09:39.896Z",
	"source": "brakeman",
	"location": "src/vendor/lib/VulnerableController.rb: Line 234",
	"references": [
		"https://owasp.org/1",
		"https://owasp.org/2"
	]
}

=== OWASP/off/example.finding.2.json
{
    "name": "SSH Protocol Version 1 Supported",
    "description": "SSH1 protocol was deprecated due to multiple vulnerabilities and design flaws.\nAmong multiple vulnerabilities that exist in SSH protocol Version 1 are:\n<UL>\n<LI>a CRC32 compensation attack detector vulnerability (buffer overflow)\n<LI>an unauthorized sessi",
    "detail": "SSH1 supported\tyes\nSupported authentications for SSH1\tRSA,password\nSupported ciphers for SSH1\t3des,blowfish",
    "severity": 4,
    "confidence": "high",
    "timestamp": "2020-07-10T07:28:10Z",
    "location": {
      "hostname": "demo03.s02.sjc01.qualys.com",
      "ipv4": "64.41.200.233",
      "port": 22,
      "protocol": "tcp"
    },
    "source": "QUALYS",
    "tags": [
      "Linux 2.4-2.6",
      "Embedded Device",
      "F5 Networks Big-IP",
      "Integrated Dell Remote Access Controller",
      "Linux 2.4-2.6",
      "Embedded De..."
    ],
    "references": [
      {
        "QID": "38304"
      }
    ]
  }
